{{ $attendees := (add1 .Values.attendees | int) }}
{{- range $attendee := untilStep 1 $attendees 1 }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-gateway
  namespace: user{{ $attendee }}-peachpal
  labels:
    app: fmstack-nlp
data:
  config.yaml: |
    orchestrator:
      host: "localhost"
      port: 8032
    detectors:
      - name: regex_competitor
        input: true
        output: true
        detector_params:
          regex:    
            - \b(?i:orange|apple|cranberry|pineapple|grape)\b
    routes:
      - name: all
        detectors:
          - regex_competitor
          # add more as we go
      - name: passthrough
        detectors:
{{- end }}